name: campus_connecy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animated_custom_dropdown: ^3.1.1
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  build_runner: ^2.4.9
  cloud_firestore: ^5.0.2
  copy_with_extension: ^5.0.4
  copy_with_extension_gen: ^5.0.4
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  ionicons: ^0.2.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/

  fonts:
    - family: Futura
      fonts:
        - asset: fonts/FuturaPTBook.otf